### ISSUE TITLE
Cannot see or make any Pokemon

### ISSUE THREAD

**Issue by Maker-Mark** [myarmolinsky/Ponkemo-v2#2]
Love the app, easy to use!
I got it all set up, created an account and logged in but I don't seem to see any pokemon or have the ability to make one.
Could the server be hosted somewhere so that I can see all the pokemon you have available?

Thanks!

**Comment by myarmolinsky** [comment]
Thank you for giving the app a shot!
I do not push the db and production files with my code so for the moment you cannot see any Pokemon unless you create your own db file in the config folder after cloning the repository.  Once I feel the app is ready, I will deploy it with Heroku and will add a link to it in the repository.
Until then, if you wish to see Pokemon you must create your own db and create a db file in the config folder with the appropriate information to connect to it.  Note that in order to edit or create Pokemon you need to have admin privileges.  By default, users have non-admin privileges; in order to grant a user admin privileges, currently the only way to do so is to edit that user property in your db.

I hope that addresses the issue, let me know if there is anything else I can help with!
Thank you again for checking out the app and giving it a shot!

**Comment by Maker-Mark** [comment]
@myarmolinsky Thanks for the update and response. Looks like the URI is valid but does not accept public, non-whitelisted ips... can you make that open so that I and other users can connect with that readonly connection string?

**Comment by myarmolinsky** [comment]
@Maker-Mark The URI should be fixed now.  Upon testing it I found that I was getting an auth error so I changed the password figuring I just gave the wrong one.  That turned out to be the case, just an incorrect password.  You should be able to use the URI now!

Let me know if there is anything else
